Repository caseypugh/helium-validator-k8s, pull requests merged in 2021-07, with the labels that each got.

#9 Validator dashboard import via ConfigMap
  README.md
  k8s/grafana/grafana-helium-api-datasource.yml
  k8s/grafana/grafana-validator-dashboard.yml
  scripts/dashboard/configs/dashboard.json
  scripts/dashboard/configs/helium-datasource.json
  scripts/dashboard/configs/values.yml
  scripts/dashboard/download
  scripts/dashboard/helper
  scripts/dashboard/install
  scripts/dashboard/monitor
  scripts/dashboard/setup
  scripts/dashboard/sync
  scripts/deploy
  scripts/helper
  scripts/validator
Labels: enhancement

#12 bunch of patches to swarm-keys script
  scripts/swarm-keys
Labels: bug

#17 bash linting
  scripts/dashboard/download
  scripts/dashboard/monitor
  scripts/dashboard/setup
  scripts/deploy
  scripts/helper
  scripts/restart
  scripts/setup-k8s-dashboard
  scripts/snapshot
  scripts/swarm-keys
  scripts/validator
Labels: bug

#18 Run a testnet k8s cluster
  k8s/grafana/grafana-validator-dashboard.yml
  k8s/validator-setup.sh
  scripts/dashboard/download
  scripts/deploy
Labels: enhancement

#19 Remote Grafana access
  README.md
  k8s/grafana/external-dns-service.yml
  k8s/grafana/external-dns-values.yml
  k8s/grafana/helium-api-datasource.yml
  k8s/grafana/validator-dashboard.yml
  scripts/dashboard/setup
  scripts/dashboard/values.yml
Labels: enhancement

#21 Minor updates
  .env.sample
  .gitignore
  README.md
  k8s/helium-ns.yml
  k8s/helium-validators-configmap.yml
  k8s/validator-setup.sh
  k8s/validator.yml
  scripts/deploy
  scripts/do-node-health-check
  scripts/helper
  scripts/restart
  scripts/setup-k8s-dashboard
  scripts/snapshot
  scripts/swarm-keys
  scripts/validator
Labels: bug, enhancement

#26 Set fixed validator version
  .env.sample
  README.md
  k8s/helium-validators-configmap.yml
  k8s/validator.yml
  scripts/deploy
Labels: enhancement
